# Webscraping ______________________

In [1]:
### imports
import requests
import io
import pandas as pd
import re

from bs4 import BeautifulSoup as bs

In [2]:
### config
URL = "https://www.billboard.com/charts/hot-100/"

In [3]:
### request url and let bs work
response = requests.get(URL)
soup = bs(response.text, "html.parser")

# cant print huge stuff in notebook w/o changing settings
#print(soup.prettify())

In [4]:
### inspect source and grab what you think holds a song row
cards = soup.select("ul.o-chart-results-list-row")
### check that there is 100 songs/rows/cards
print(len(cards))

100

In [5]:
### run thru cards to see if we like 
for card in cards:
    print(card.get_text(" | ", strip=True).split(" | "))
    print("----------")

['1', "Choosin' Texas", 'Ella Langley', 'LW', '2', 'PEAK', '1', 'WEEKS', '24', 'LW', '2', 'PEAK', '1', 'WEEKS', '24']
----------
['2', 'Swim', 'BTS', 'LW', '1', 'PEAK', '1', 'WEEKS', '2', 'LW', '1', 'PEAK', '1', 'WEEKS', '2']
----------
['3', 'Man I Need', 'Olivia Dean', 'LW', '3', 'PEAK', '2', 'WEEKS', '32', 'LW', '3', 'PEAK', '2', 'WEEKS', '32']
----------
['4', 'I Just Might', 'Bruno Mars', 'LW', '4', 'PEAK', '1', 'WEEKS', '12', 'LW', '4', 'PEAK', '1', 'WEEKS', '12']
----------
['5', 'Ordinary', 'Alex Warren', 'LW', '5', 'PEAK', '1', 'WEEKS', '59', 'LW', '5', 'PEAK', '1', 'WEEKS', '59']
----------
['6', 'So Easy (To Fall In Love)', 'Olivia Dean', 'LW', '7', 'PEAK', '6', 'WEEKS', '27', 'LW', '7', 'PEAK', '6', 'WEEKS', '27']
----------
['7', 'Golden', 'HUNTR/X: EJAE, Audrey Nuna & REI AMI', 'LW', '6', 'PEAK', '1', 'WEEKS', '41', 'LW', '6', 'PEAK', '1', 'WEEKS', '41']
----------
['8', 'Stateside', 'PinkPantheress', 'With', 'Zara Larsson', 'LW', '8', 'PEAK', '6', 'WEEKS', '13', 'LW', '8', 'PEAK', '6', 'WEEKS', '13']
----------
['9', 'The Fate Of Ophelia', 'Taylor Swift', 'LW', '9', 'PEAK', '1', 'WEEKS', '26', 'LW', '9', 'PEAK', '1', 'WEEKS', '26']
----------
['10', 'Folded', 'Kehlani', 'LW', '10', 'PEAK', '6', 'WEEKS', '42', 'LW', '10', 'PEAK', '6', 'WEEKS', '42']
----------
['11', 'Where Is My Husband!', 'RAYE', 'LW', '17', 'PEAK', '11', 'WEEKS', '27', 'LW', '17', 'PEAK', '11', 'WEEKS', '27']
----------
['12', 'Be Her', 'Ella Langley', 'LW', '13', 'PEAK', '12', 'WEEKS', '7', 'LW', '13', 'PEAK', '12', 'WEEKS', '7']
----------
['13', 'Opalite', 'Taylor Swift', 'LW', '12', 'PEAK', '1', 'WEEKS', '26', 'LW', '12', 'PEAK', '1', 'WEEKS', '26']
----------
['14', 'Sleepless In A Hotel Room', 'Luke Combs', 'LW', '11', 'PEAK', '11', 'WEEKS', '12', 'LW', '11', 'PEAK', '11', 'WEEKS', '12']
----------
['15', 'Risk It All', 'Bruno Mars', 'LW', '15', 'PEAK', '4', 'WEEKS', '5', 'LW', '15', 'PEAK', '4', 'WEEKS', '5']
----------
['16', 'Babydoll', 'Dominic Fike', 'LW', '16', 'PEAK', '16', 'WEEKS', '8', 'LW', '16', 'PEAK', '16', 'WEEKS', '8']
----------
['17', 'Iloveitiloveitiloveit', 'Bella Kay', 'LW', '20', 'PEAK', '17', 'WEEKS', '7', 'LW', '20', 'PEAK', '17', 'WEEKS', '7']
----------
['18', 'Dracula', 'Tame Impala', '&', 'JENNIE', 'LW', '24', 'PEAK', '18', 'WEEKS', '27', 'LW', '24', 'PEAK', '18', 'WEEKS', '27']
----------
['19', 'E85', 'Don Toliver', 'LW', '21', 'PEAK', '15', 'WEEKS', '9', 'LW', '21', 'PEAK', '15', 'WEEKS', '9']
----------
['20', 'Yukon', 'Justin Bieber', 'LW', '23', 'PEAK', '17', 'WEEKS', '38', 'LW', '23', 'PEAK', '17', 'WEEKS', '38']
----------
['21', 'NEW', 'NEW', 'Father', 'Ye &', 'Travis Scott', 'LW', '-', 'PEAK', '21', 'WEEKS', '1', 'LW', '-', 'PEAK', '21', 'WEEKS', '1']
----------
['22', 'Be By You', 'Luke Combs', 'LW', '18', 'PEAK', '12', 'WEEKS', '7', 'LW', '18', 'PEAK', '12', 'WEEKS', '7']
----------
['23', 'American Girls', 'Harry Styles', 'LW', '19', 'PEAK', '4', 'WEEKS', '4', 'LW', '19', 'PEAK', '4', 'WEEKS', '4']
----------
['24', 'DTMF', 'Bad Bunny', 'LW', '22', 'PEAK', '1', 'WEEKS', '29', 'LW', '22', 'PEAK', '1', 'WEEKS', '29']
----------
['25', 'Homewrecker', 'sombr', 'LW', '26', 'PEAK', '24', 'WEEKS', '8', 'LW', '26', 'PEAK', '24', 'WEEKS', '8']
----------
['26', 'Body', 'Don Toliver', 'LW', '27', 'PEAK', '14', 'WEEKS', '9', 'LW', '27', 'PEAK', '14', 'WEEKS', '9']
----------
['27', 'NEW', 'NEW', 'All The Love', 'Ye &', 'Andre Troutman', 'LW', '-', 'PEAK', '27', 'WEEKS', '1', 'LW', '-', 'PEAK', '27', 'WEEKS', '1']
----------
['28', 'The Fall', 'Cody Johnson', 'LW', '30', 'PEAK', '28', 'WEEKS', '27', 'LW', '30', 'PEAK', '28', 'WEEKS', '27']
----------
['29', 'Die On This Hill', 'Sienna Spiro', 'LW', '29', 'PEAK', '19', 'WEEKS', '15', 'LW', '29', 'PEAK', '19', 'WEEKS', '15']
----------
['30', 'Change My Mind', 'Riley Green', 'LW', '38', 'PEAK', '30', 'WEEKS', '9', 'LW', '38', 'PEAK', '30', 'WEEKS', '9']
----------
['31', 'Pop Dat Thang', 'DaBaby', 'LW', '45', 'PEAK', '31', 'WEEKS', '9', 'LW', '45', 'PEAK', '31', 'WEEKS', '9']
----------
['32', 'White Keys', 'Dominic Fike', 'LW', '32', 'PEAK', '32', 'WEEKS', '6', 'LW', '32', 'PEAK', '32', 'WEEKS', '6']
----------
['33', 'Fever Dream', 'Alex Warren', 'LW', '33', 'PEAK', '21', 'WEEKS', '5', 'LW', '33', 'PEAK', '21', 'WEEKS', '5']
----------
['34', "Let 'Em Know", 'T.I.', 'LW', '40', 'PEAK', '34', 'WEEKS', '10', 'LW', '40', 'PEAK', '34', 'WEEKS', '10']
----------
['35', 'Elizabeth Taylor', 'Taylor Swift', 'LW', '65', 'PEAK', '3', 'WEEKS', '22', 'LW', '65', 'PEAK', '3', 'WEEKS', '22']
----------
['36', 'Lush Life', 'Zara Larsson', 'LW', '44', 'PEAK', '36', 'WEEKS', '16', 'LW', '44', 'PEAK', '36', 'WEEKS', '16']
----------
['37', 'What You Saying', 'Lil Uzi Vert', 'LW', '34', 'PEAK', '12', 'WEEKS', '14', 'LW', '34', 'PEAK', '12', 'WEEKS', '14']
----------
['38', 'The Great Divide', 'Noah Kahan', 'LW', '37', 'PEAK', '6', 'WEEKS', '9', 'LW', '37', 'PEAK', '6', 'WEEKS', '9']
----------
['39', 'Days Like These', 'Luke Combs', 'LW', '31', 'PEAK', '31', 'WEEKS', '23', 'LW', '31', 'PEAK', '31', 'WEEKS', '23']
----------
['40', 'NEW', 'NEW', 'King', 'Ye', 'LW', '-', 'PEAK', '40', 'WEEKS', '1', 'LW', '-', 'PEAK', '40', 'WEEKS', '1']
----------
['41', 'Motion Party', 'BossMan Dlow', 'LW', '48', 'PEAK', '41', 'WEEKS', '3', 'LW', '48', 'PEAK', '41', 'WEEKS', '3']
----------
['42', 'Body To Body', 'BTS', 'LW', '25', 'PEAK', '25', 'WEEKS', '2', 'LW', '25', 'PEAK', '25', 'WEEKS', '2']
----------
['43', 'Midnight Sun', 'Zara Larsson', 'LW', '49', 'PEAK', '39', 'WEEKS', '11', 'LW', '49', 'PEAK', '39', 'WEEKS', '11']
----------
['44', 'NEW', 'NEW', 'Punch Drunk', 'Ye', 'LW', '-', 'PEAK', '44', 'WEEKS', '1', 'LW', '-', 'PEAK', '44', 'WEEKS', '1']
----------
['45', 'Brunette', 'Tucker Wetmore', 'LW', '51', 'PEAK', '44', 'WEEKS', '14', 'LW', '51', 'PEAK', '44', 'WEEKS', '14']
----------
['46', 'Loving Life Again', 'Ella Langley', 'LW', '55', 'PEAK', '46', 'WEEKS', '2', 'LW', '55', 'PEAK', '46', 'WEEKS', '2']
----------
['47', 'McArthur', 'HARDY', ',', 'Eric Church', ',', 'Morgan Wallen', '&', 'Tim McGraw', 'LW', '54', 'PEAK', '31', 'WEEKS', '9', 'LW', '54', 'PEAK', '31', 'WEEKS', '9']
----------
['48', 'Porch Light', 'Noah Kahan', 'LW', '42', 'PEAK', '20', 'WEEKS', '3', 'LW', '42', 'PEAK', '20', 'WEEKS', '3']
----------
['49', 'NEW', 'NEW', 'Whatever Works', 'Ye', 'LW', '-', 'PEAK', '49', 'WEEKS', '1', 'LW', '-', 'PEAK', '49', 'WEEKS', '1']
----------
['50', 'When Did You Get Hot?', 'Sabrina Carpenter', 'LW', '58', 'PEAK', '17', 'WEEKS', '29', 'LW', '58', 'PEAK', '17', 'WEEKS', '29']
----------
['51', 'NEW', 'NEW', 'This A Must', 'Ye', 'LW', '-', 'PEAK', '51', 'WEEKS', '1', 'LW', '-', 'PEAK', '51', 'WEEKS', '1']
----------
['52', 'Raindance', 'Dave', '&', 'Tems', 'LW', '57', 'PEAK', '52', 'WEEKS', '9', 'LW', '57', 'PEAK', '52', 'WEEKS', '9']
----------
['53', 'Chanel', 'Tyla', 'LW', '59', 'PEAK', '43', 'WEEKS', '16', 'LW', '59', 'PEAK', '43', 'WEEKS', '16']
----------
['54', 'Dandelion', 'Ella Langley', 'LW', '60', 'PEAK', '37', 'WEEKS', '9', 'LW', '60', 'PEAK', '37', 'WEEKS', '9']
----------
['55', 'Rethink Some Things', 'Luke Combs', 'LW', '46', 'PEAK', '46', 'WEEKS', '2', 'LW', '46', 'PEAK', '46', 'WEEKS', '2']
----------
['56', "I Ain't Coming Back", 'Morgan Wallen', 'Featuring', 'Post Malone', 'LW', '66', 'PEAK', '8', 'WEEKS', '42', 'LW', '66', 'PEAK', '8', 'WEEKS', '42']
----------
['57', 'NEW', 'NEW', 'Preacher Man', 'Ye', 'LW', '-', 'PEAK', '57', 'WEEKS', '1', 'LW', '-', 'PEAK', '57', 'WEEKS', '1']
----------
['58', 'Aperture', 'Harry Styles', 'LW', '39', 'PEAK', '1', 'WEEKS', '10', 'LW', '39', 'PEAK', '1', 'WEEKS', '10']
----------
['59', 'NEW', 'NEW', "Mama's Favorite", 'Ye', 'LW', '-', 'PEAK', '59', 'WEEKS', '1', 'LW', '-', 'PEAK', '59', 'WEEKS', '1']
----------
['60', 'In My Room', 'Julia Wolf', 'LW', '67', 'PEAK', '60', 'WEEKS', '4', 'LW', '67', 'PEAK', '60', 'WEEKS', '4']
----------
['61', 'NEW', 'NEW', 'Bully', 'Ye & CeeLo Green', 'LW', '-', 'PEAK', '61', 'WEEKS', '1', 'LW', '-', 'PEAK', '61', 'WEEKS', '1']
----------
['62', 'NEW', 'NEW', 'Highs And Lows', 'Ye', 'LW', '-', 'PEAK', '62', 'WEEKS', '1', 'LW', '-', 'PEAK', '62', 'WEEKS', '1']
----------
['63', "Time's Ticking", 'Justin Moore', 'LW', '75', 'PEAK', '63', 'WEEKS', '7', 'LW', '75', 'PEAK', '63', 'WEEKS', '7']
----------
['64', 'Hooligan', 'BTS', 'LW', '35', 'PEAK', '35', 'WEEKS', '2', 'LW', '35', 'PEAK', '35', 'WEEKS', '2']
----------
['65', 'Earrings', 'Malcolm Todd', 'LW', '85', 'PEAK', '65', 'WEEKS', '5', 'LW', '85', 'PEAK', '65', 'WEEKS', '5']
----------
['66', "What He'll Never Have", 'Dylan Scott', 'LW', '74', 'PEAK', '66', 'WEEKS', '5', 'LW', '74', 'PEAK', '66', 'WEEKS', '5']
----------
['67', 'NEW', 'NEW', 'Sisters And Brothers', 'Ye', 'LW', '-', 'PEAK', '67', 'WEEKS', '1', 'LW', '-', 'PEAK', '67', 'WEEKS', '1']
----------
['68', "Ain't A Bad Life", 'Thomas Rhett', 'Featuring', 'Jordan Davis', 'LW', '71', 'PEAK', '65', 'WEEKS', '9', 'LW', '71', 'PEAK', '65', 'WEEKS', '9']
----------
['69', 'NEW', 'NEW', 'Younger You (From The "Hannah Montana 20th Anniversary Special")', 'Miley Cyrus', 'LW', '-', 'PEAK', '69', 'WEEKS', '1', 'LW', '-', 'PEAK', '69', 'WEEKS', '1']
----------
['70', 'Turn This Truck Around', 'Jordan Davis', 'LW', '73', 'PEAK', '69', 'WEEKS', '5', 'LW', '73', 'PEAK', '69', 'WEEKS', '5']
----------
['71', 'Beautiful Things', 'Megan Moroney', 'LW', '72', 'PEAK', '32', 'WEEKS', '18', 'LW', '72', 'PEAK', '32', 'WEEKS', '18']
----------
['72', 'NEW', 'NEW', "I Can't Wait", 'Ye', 'LW', '-', 'PEAK', '72', 'WEEKS', '1', 'LW', '-', 'PEAK', '72', 'WEEKS', '1']
----------
['73', 'Normal', 'BTS', 'LW', '41', 'PEAK', '41', 'WEEKS', '2', 'LW', '41', 'PEAK', '41', 'WEEKS', '2']
----------
['74', 'FYA', 'BTS', 'LW', '36', 'PEAK', '36', 'WEEKS', '2', 'LW', '36', 'PEAK', '36', 'WEEKS', '2']
----------
['75', '2.0', 'BTS', 'LW', '50', 'PEAK', '50', 'WEEKS', '2', 'LW', '50', 'PEAK', '50', 'WEEKS', '2']
----------
['76', 'Ends Of The Earth', 'Ty Myers', 'LW', '76', 'PEAK', '72', 'WEEKS', '11', 'LW', '76', 'PEAK', '72', 'WEEKS', '11']
----------
['77', "Freakin' Out", 'Dexter And The Moonrocks', 'LW', '91', 'PEAK', '77', 'WEEKS', '2', 'LW', '91', 'PEAK', '77', 'WEEKS', '2']
----------
['78', 'Rein Me In', 'Sam Fender', '& Olivia Dean', 'LW', '78', 'PEAK', '77', 'WEEKS', '3', 'LW', '78', 'PEAK', '77', 'WEEKS', '3']
----------
['79', 'Coming Up Roses', 'Harry Styles', 'LW', '64', 'PEAK', '18', 'WEEKS', '4', 'LW', '64', 'PEAK', '18', 'WEEKS', '4']
----------
['80', 'The Visitor', 'Sienna Spiro', 'LW', '62', 'PEAK', '43', 'WEEKS', '3', 'LW', '62', 'PEAK', '43', 'WEEKS', '3']
----------
['81', 'NEW', 'NEW', 'Last Breath', 'Ye &', 'Peso Pluma', 'LW', '-', 'PEAK', '81', 'WEEKS', '1', 'LW', '-', 'PEAK', '81', 'WEEKS', '1']
----------
['82', 'NEW', 'NEW', 'White Lines', 'Ye &', 'Andre Troutman', 'LW', '-', 'PEAK', '82', 'WEEKS', '1', 'LW', '-', 'PEAK', '82', 'WEEKS', '1']
----------
['83', 'Go Away', 'Weezer', 'LW', '90', 'PEAK', '83', 'WEEKS', '2', 'LW', '90', 'PEAK', '83', 'WEEKS', '2']
----------
['84', 'Aliens', 'BTS', 'LW', '47', 'PEAK', '47', 'WEEKS', '2', 'LW', '47', 'PEAK', '47', 'WEEKS', '2']
----------
['85', 'NEW', 'NEW', 'Beauty And The Beast', 'Ye', 'LW', '-', 'PEAK', '85', 'WEEKS', '1', 'LW', '-', 'PEAK', '85', 'WEEKS', '1']
----------
['86', "Don't We", 'Morgan Wallen', 'LW', '88', 'PEAK', '48', 'WEEKS', '8', 'LW', '88', 'PEAK', '48', 'WEEKS', '8']
----------
['87', 'NEW', 'NEW', 'Circles', 'Ye', 'LW', '-', 'PEAK', '87', 'WEEKS', '1', 'LW', '-', 'PEAK', '87', 'WEEKS', '1']
----------
['88', 'Dry Spell', 'Kacey Musgraves', 'LW', '80', 'PEAK', '55', 'WEEKS', '3', 'LW', '80', 'PEAK', '55', 'WEEKS', '3']
----------
['89', 'What You Need', 'Tems', 'LW', '98', 'PEAK', '89', 'WEEKS', '3', 'LW', '98', 'PEAK', '89', 'WEEKS', '3']
----------
['90', 'Like Animals', 'BTS', 'LW', '53', 'PEAK', '53', 'WEEKS', '2', 'LW', '53', 'PEAK', '53', 'WEEKS', '2']
----------
['91', 'Zoo', 'Shakira', 'LW', '81', 'PEAK', '73', 'WEEKS', '8', 'LW', '81', 'PEAK', '73', 'WEEKS', '8']
----------
['92', 'Dano', 'Peso Pluma', '& Tito Double P', 'LW', '87', 'PEAK', '75', 'WEEKS', '6', 'LW', '87', 'PEAK', '75', 'WEEKS', '6']
----------
['93', 'Who Knows', 'Daniel Caesar', 'LW', '83', 'PEAK', '52', 'WEEKS', '13', 'LW', '83', 'PEAK', '52', 'WEEKS', '13']
----------
['94', "They Don't Know 'bout Us", 'BTS', 'LW', '56', 'PEAK', '56', 'WEEKS', '2', 'LW', '56', 'PEAK', '56', 'WEEKS', '2']
----------
['95', 'Mrs. Trendsetter', 'Lil Baby', 'LW', '84', 'PEAK', '64', 'WEEKS', '7', 'LW', '84', 'PEAK', '64', 'WEEKS', '7']
----------
['96', 'Merry Go Round', 'BTS', 'LW', '52', 'PEAK', '52', 'WEEKS', '2', 'LW', '52', 'PEAK', '52', 'WEEKS', '2']
----------
['97', 'NEW', 'NEW', 'Griddle', 'Yeat &', 'Don Toliver', 'LW', '-', 'PEAK', '97', 'WEEKS', '1', 'LW', '-', 'PEAK', '97', 'WEEKS', '1']
----------
['98', 'NEW', 'NEW', 'Silent Treatment', 'Freya Skye', 'LW', '-', 'PEAK', '98', 'WEEKS', '1', 'LW', '-', 'PEAK', '98', 'WEEKS', '1']
----------
['99', 'Taste Back', 'Harry Styles', 'LW', '69', 'PEAK', '17', 'WEEKS', '4', 'LW', '69', 'PEAK', '17', 'WEEKS', '4']
----------
['100', 'Plastic Cigarette', 'Zach Bryan', 'LW', '89', 'PEAK', '13', 'WEEKS', '11', 'LW', '89', 'PEAK', '13', 'WEEKS', '11']
----------

In [6]:
### run thru the cards/rows now that we know its structure and create df
rows = []

### for song_details in song_container
for card in cards:
    parts = card.get_text(" | ", strip=True).split(" | ")

    rank = parts[0]
    lw = parts[parts.index("LW") + 1]
    peak = parts[parts.index("PEAK") + 1]
    weeks = parts[parts.index("WEEKS") + 1]

    title_artist_parts = parts[1:parts.index("LW")]
    title_artist_parts = [p for p in title_artist_parts if p != "NEW"]
    title = title_artist_parts[0]
    artist = " ".join(title_artist_parts[1:])

    rows.append({
        "Rank": rank,
        "Title": title,
        "Artist": artist,
        "LW": lw,
        "Peak": peak,
        "Weeks": weeks
    })

top100_df = pd.DataFrame(rows)
top100_df

   Rank              Title              Artist  LW Peak Weeks
0     1     Choosin' Texas        Ella Langley   2    1    24
1     2               Swim                 BTS   1    1     2
2     3         Man I Need         Olivia Dean   3    2    32
3     4       I Just Might          Bruno Mars   4    1    12
4     5           Ordinary         Alex Warren   5    1    59
..  ...                ...                 ...  ..  ...   ...
95   96     Merry Go Round                 BTS  52   52     2
96   97            Griddle  Yeat & Don Toliver   -   97     1
97   98   Silent Treatment          Freya Skye   -   98     1
98   99         Taste Back        Harry Styles  69   17     4
99  100  Plastic Cigarette          Zach Bryan  89   13    11

[100 rows x 6 columns]

# extract out the This Week, artist, song, Last Week, Peak Position, and Weeks on Chart values into a pandas DataFrame

In [7]:
### fetch song titles[]
# clean = re.sub(r'[\t\n]+', '', text)
song_titles = soup.find_all('h3', class_='c-title a-font-basic u-letter-spacing-0010 u-max-width-397 lrv-u-font-size-16 lrv-u-font-size-14@mobile-max u-line-height-22px u-word-spacing-0063 u-line-height-normal@mobile-max a-truncate-ellipsis-2line lrv-u-margin-b-025 lrv-u-margin-b-00@mobile-max')
song_titles = [(re.sub(r'[\t\n]+', '', x.text)) for x in song_titles]
song_titles

["Choosin' Texas",
 'Swim',
 'Man I Need',
 'I Just Might',
 'Ordinary',
 'So Easy (To Fall In Love)',
 'Golden',
 'Stateside',
 'The Fate Of Ophelia',
 'Folded',
 'Where Is My Husband!',
 'Be Her',
 'Opalite',
 'Sleepless In A Hotel Room',
 'Risk It All',
 'Babydoll',
 'Iloveitiloveitiloveit',
 'Dracula',
 'E85',
 'Yukon',
 'Father',
 'Be By You',
 'American Girls',
 'DTMF',
 'Homewrecker',
 'Body',
 'All The Love',
 'The Fall',
 'Die On This Hill',
 'Change My Mind',
 'Pop Dat Thang',
 'White Keys',
 'Fever Dream',
 "Let 'Em Know",
 'Elizabeth Taylor',
 'Lush Life',
 'What You Saying',
 'The Great Divide',
 'Days Like These',
 'King',
 'Motion Party',
 'Body To Body',
 'Midnight Sun',
 'Punch Drunk',
 'Brunette',
 'Loving Life Again',
 'McArthur',
 'Porch Light',
 'Whatever Works',
 'When Did You Get Hot?',
 'This A Must',
 'Raindance',
 'Chanel',
 'Dandelion',
 'Rethink Some Things',
 "I Ain't Coming Back",
 'Preacher Man',
 'Aperture',
 "Mama's Favorite",
 'In My Room',
 'Bully',
 'Highs And Lows',
 "Time's Ticking",
 'Hooligan',
 'Earrings',
 "What He'll Never Have",
 'Sisters And Brothers',
 "Ain't A Bad Life",
 'Younger You (From The "Hannah Montana 20th Anniversary Special")',
 'Turn This Truck Around',
 'Beautiful Things',
 "I Can't Wait",
 'Normal',
 'FYA',
 '2.0',
 'Ends Of The Earth',
 "Freakin' Out",
 'Rein Me In',
 'Coming Up Roses',
 'The Visitor',
 'Last Breath',
 'White Lines',
 'Go Away',
 'Aliens',
 'Beauty And The Beast',
 "Don't We",
 'Circles',
 'Dry Spell',
 'What You Need',
 'Like Animals',
 'Zoo',
 'Dano',
 'Who Knows',
 "They Don't Know 'bout Us",
 'Mrs. Trendsetter',
 'Merry Go Round',
 'Griddle',
 'Silent Treatment',
 'Taste Back',
 'Plastic Cigarette']

In [8]:
### fetch artists[]
# clean = re.sub(r'[\t\n]+', '', text)

# <span class="
#     c-label a-no-trucate
#     a-font-secondary u-font-size-15 u-font-size-13@mobile-max u-line-height-18px@mobile-max u-letter-spacing-0010 u-line-height-21px
#     a-children-link-color-black a-children-link-color-brand-secondary:hover
#     lrv-a-children-link-decoration-underline:hover
#     lrv-u-display-block a-truncate-ellipsis-2line u-max-width-397 u-max-width-230@tablet-only u-max-width-300@mobile-max">
# 							<a href="https://www.billboard.com/artist/bts/">BTS</a>						</span>


artists = soup.find_all('span', class_='c-label a-no-trucate a-font-secondary u-font-size-15 u-font-size-13@mobile-max u-line-height-18px@mobile-max u-letter-spacing-0010 u-line-height-21px a-children-link-color-black a-children-link-color-brand-secondary:hover lrv-a-children-link-decoration-underline:hover lrv-u-display-block a-truncate-ellipsis-2line u-max-width-397 u-max-width-230@tablet-only u-max-width-300@mobile-max')
artists = [(re.sub(r'[\t\n]+', '', x.text)).strip() for x in artists]
artists

['Ella Langley',
 'BTS',
 'Olivia Dean',
 'Bruno Mars',
 'Alex Warren',
 'Olivia Dean',
 'HUNTR/X: EJAE, Audrey Nuna & REI AMI',
 'PinkPantheress With Zara Larsson',
 'Taylor Swift',
 'Kehlani',
 'RAYE',
 'Ella Langley',
 'Taylor Swift',
 'Luke Combs',
 'Bruno Mars',
 'Dominic Fike',
 'Bella Kay',
 'Tame Impala & JENNIE',
 'Don Toliver',
 'Justin Bieber',
 'Ye & Travis Scott',
 'Luke Combs',
 'Harry Styles',
 'Bad Bunny',
 'sombr',
 'Don Toliver',
 'Ye & Andre Troutman',
 'Cody Johnson',
 'Sienna Spiro',
 'Riley Green',
 'DaBaby',
 'Dominic Fike',
 'Alex Warren',
 'T.I.',
 'Taylor Swift',
 'Zara Larsson',
 'Lil Uzi Vert',
 'Noah Kahan',
 'Luke Combs',
 'Ye',
 'BossMan Dlow',
 'BTS',
 'Zara Larsson',
 'Ye',
 'Tucker Wetmore',
 'Ella Langley',
 'HARDY, Eric Church, Morgan Wallen & Tim McGraw',
 'Noah Kahan',
 'Ye',
 'Sabrina Carpenter',
 'Ye',
 'Dave & Tems',
 'Tyla',
 'Ella Langley',
 'Luke Combs',
 'Morgan Wallen Featuring Post Malone',
 'Ye',
 'Harry Styles',
 'Ye',
 'Julia Wolf',
 'Ye & CeeLo Green',
 'Ye',
 'Justin Moore',
 'BTS',
 'Malcolm Todd',
 'Dylan Scott',
 'Ye',
 'Thomas Rhett Featuring Jordan Davis',
 'Miley Cyrus',
 'Jordan Davis',
 'Megan Moroney',
 'Ye',
 'BTS',
 'BTS',
 'BTS',
 'Ty Myers',
 'Dexter And The Moonrocks',
 'Sam Fender & Olivia Dean',
 'Harry Styles',
 'Sienna Spiro',
 'Ye & Peso Pluma',
 'Ye & Andre Troutman',
 'Weezer',
 'BTS',
 'Ye',
 'Morgan Wallen',
 'Ye',
 'Kacey Musgraves',
 'Tems',
 'BTS',
 'Shakira',
 'Peso Pluma & Tito Double P',
 'Daniel Caesar',
 'BTS',
 'Lil Baby',
 'BTS',
 'Yeat & Don Toliver',
 'Freya Skye',
 'Harry Styles',
 'Zach Bryan']

In [9]:
### see if there's a pattern inside the span class
rows = soup.select("li.o-chart-results-list__item")
i=0
for row in rows:
    print("["+str(i)+"]"+row.get_text(" | ", strip=True))
    print("-" * 80)
    i += 1

[0]1
--------------------------------------------------------------------------------
[1]
--------------------------------------------------------------------------------
[2]
--------------------------------------------------------------------------------
[3]Choosin' Texas | Ella Langley
--------------------------------------------------------------------------------
[4]
--------------------------------------------------------------------------------
[5]2
--------------------------------------------------------------------------------
[6]1
--------------------------------------------------------------------------------
[7]24
--------------------------------------------------------------------------------
[8]
--------------------------------------------------------------------------------
[9]2
--------------------------------------------------------------------------------
[10]1
--------------------------------------------------------------------------------
[11]24
--------------------------------------------------------------------------------
[12]
--------------------------------------------------------------------------------
[13]
--------------------------------------------------------------------------------
[14]2
--------------------------------------------------------------------------------
[15]
--------------------------------------------------------------------------------
[16]
--------------------------------------------------------------------------------
[17]Swim | BTS
--------------------------------------------------------------------------------
[18]
--------------------------------------------------------------------------------
[19]1
--------------------------------------------------------------------------------
[20]1
--------------------------------------------------------------------------------
[21]2
--------------------------------------------------------------------------------
[22]
--------------------------------------------------------------------------------
[23]1
--------------------------------------------------------------------------------
[24]1
--------------------------------------------------------------------------------
[25]2
--------------------------------------------------------------------------------
[26]
--------------------------------------------------------------------------------
[27]
--------------------------------------------------------------------------------
[28]3
--------------------------------------------------------------------------------
[29]
--------------------------------------------------------------------------------
[30]
--------------------------------------------------------------------------------
[31]Man I Need | Olivia Dean
--------------------------------------------------------------------------------
[32]
--------------------------------------------------------------------------------
[33]3
--------------------------------------------------------------------------------
[34]2
--------------------------------------------------------------------------------
[35]32
--------------------------------------------------------------------------------
[36]
--------------------------------------------------------------------------------
[37]3
--------------------------------------------------------------------------------
[38]2
--------------------------------------------------------------------------------
[39]32
--------------------------------------------------------------------------------
[40]
--------------------------------------------------------------------------------
[41]
--------------------------------------------------------------------------------
[42]4
--------------------------------------------------------------------------------
[43]
--------------------------------------------------------------------------------
[44]
--------------------------------------------------------------------------------
[45]I Just Might | Bruno Mars
--------------------------------------------------------------------------------
[46]
--------------------------------------------------------------------------------
[47]4
--------------------------------------------------------------------------------
[48]1
--------------------------------------------------------------------------------
[49]12
--------------------------------------------------------------------------------
[50]
--------------------------------------------------------------------------------
[51]4
--------------------------------------------------------------------------------
[52]1
--------------------------------------------------------------------------------
[53]12
--------------------------------------------------------------------------------
[54]
--------------------------------------------------------------------------------
[55]
--------------------------------------------------------------------------------
[56]5
--------------------------------------------------------------------------------
[57]
--------------------------------------------------------------------------------
[58]
--------------------------------------------------------------------------------
[59]Ordinary | Alex Warren
--------------------------------------------------------------------------------
[60]
--------------------------------------------------------------------------------
[61]5
--------------------------------------------------------------------------------
[62]1
--------------------------------------------------------------------------------
[63]59
--------------------------------------------------------------------------------
[64]
--------------------------------------------------------------------------------
[65]5
--------------------------------------------------------------------------------
[66]1
--------------------------------------------------------------------------------
[67]59
--------------------------------------------------------------------------------
[68]
--------------------------------------------------------------------------------
[69]
--------------------------------------------------------------------------------
[70]6
--------------------------------------------------------------------------------
[71]
--------------------------------------------------------------------------------
[72]
--------------------------------------------------------------------------------
[73]So Easy (To Fall In Love) | Olivia Dean
--------------------------------------------------------------------------------
[74]
--------------------------------------------------------------------------------
[75]7
--------------------------------------------------------------------------------
[76]6
--------------------------------------------------------------------------------
[77]27
--------------------------------------------------------------------------------
[78]
--------------------------------------------------------------------------------
[79]7
--------------------------------------------------------------------------------
[80]6
--------------------------------------------------------------------------------
[81]27
--------------------------------------------------------------------------------
[82]
--------------------------------------------------------------------------------
[83]
--------------------------------------------------------------------------------
[84]7
--------------------------------------------------------------------------------
[85]
--------------------------------------------------------------------------------
[86]
--------------------------------------------------------------------------------
[87]Golden | HUNTR/X: EJAE, Audrey Nuna & REI AMI
--------------------------------------------------------------------------------
[88]
--------------------------------------------------------------------------------
[89]6
--------------------------------------------------------------------------------
[90]1
--------------------------------------------------------------------------------
[91]41
--------------------------------------------------------------------------------
[92]
--------------------------------------------------------------------------------
[93]6
--------------------------------------------------------------------------------
[94]1
--------------------------------------------------------------------------------
[95]41
--------------------------------------------------------------------------------
[96]
--------------------------------------------------------------------------------
[97]
--------------------------------------------------------------------------------
[98]8
--------------------------------------------------------------------------------
[99]
--------------------------------------------------------------------------------
[100]
--------------------------------------------------------------------------------
[101]Stateside | PinkPantheress | With | Zara Larsson
--------------------------------------------------------------------------------
[102]
--------------------------------------------------------------------------------
[103]8
--------------------------------------------------------------------------------
[104]6
--------------------------------------------------------------------------------
[105]13
--------------------------------------------------------------------------------
[106]
--------------------------------------------------------------------------------
[107]8
--------------------------------------------------------------------------------
[108]6
--------------------------------------------------------------------------------
[109]13
--------------------------------------------------------------------------------
[110]
--------------------------------------------------------------------------------
[111]
--------------------------------------------------------------------------------
[112]9
--------------------------------------------------------------------------------
[113]
--------------------------------------------------------------------------------
[114]
--------------------------------------------------------------------------------
[115]The Fate Of Ophelia | Taylor Swift
--------------------------------------------------------------------------------
[116]
--------------------------------------------------------------------------------
[117]9
--------------------------------------------------------------------------------
[118]1
--------------------------------------------------------------------------------
[119]26
--------------------------------------------------------------------------------
[120]
--------------------------------------------------------------------------------
[121]9
--------------------------------------------------------------------------------
[122]1
--------------------------------------------------------------------------------
[123]26
--------------------------------------------------------------------------------
[124]
--------------------------------------------------------------------------------
[125]
--------------------------------------------------------------------------------
[126]10
--------------------------------------------------------------------------------
[127]
--------------------------------------------------------------------------------
[128]
--------------------------------------------------------------------------------
[129]Folded | Kehlani
--------------------------------------------------------------------------------
[130]
--------------------------------------------------------------------------------
[131]10
--------------------------------------------------------------------------------
[132]6
--------------------------------------------------------------------------------
[133]42
--------------------------------------------------------------------------------
[134]
--------------------------------------------------------------------------------
[135]10
--------------------------------------------------------------------------------
[136]6
--------------------------------------------------------------------------------
[137]42
--------------------------------------------------------------------------------
[138]
--------------------------------------------------------------------------------
[139]
--------------------------------------------------------------------------------
[140]11
--------------------------------------------------------------------------------
[141]
--------------------------------------------------------------------------------
[142]
--------------------------------------------------------------------------------
[143]Where Is My Husband! | RAYE
--------------------------------------------------------------------------------
[144]
--------------------------------------------------------------------------------
[145]17
--------------------------------------------------------------------------------
[146]11
--------------------------------------------------------------------------------
[147]27
--------------------------------------------------------------------------------
[148]
--------------------------------------------------------------------------------
[149]17
--------------------------------------------------------------------------------
[150]11
--------------------------------------------------------------------------------
[151]27
--------------------------------------------------------------------------------
[152]
--------------------------------------------------------------------------------
[153]
--------------------------------------------------------------------------------
[154]12
--------------------------------------------------------------------------------
[155]
--------------------------------------------------------------------------------
[156]
--------------------------------------------------------------------------------
[157]Be Her | Ella Langley
--------------------------------------------------------------------------------
[158]
--------------------------------------------------------------------------------
[159]13
--------------------------------------------------------------------------------
[160]12
--------------------------------------------------------------------------------
[161]7
--------------------------------------------------------------------------------
[162]
--------------------------------------------------------------------------------
[163]13
--------------------------------------------------------------------------------
[164]12
--------------------------------------------------------------------------------
[165]7
--------------------------------------------------------------------------------
[166]
--------------------------------------------------------------------------------
[167]
--------------------------------------------------------------------------------
[168]13
--------------------------------------------------------------------------------
[169]
--------------------------------------------------------------------------------
[170]
--------------------------------------------------------------------------------
[171]Opalite | Taylor Swift
--------------------------------------------------------------------------------
[172]
--------------------------------------------------------------------------------
[173]12
--------------------------------------------------------------------------------
[174]1
--------------------------------------------------------------------------------
[175]26
--------------------------------------------------------------------------------
[176]
--------------------------------------------------------------------------------
[177]12
--------------------------------------------------------------------------------
[178]1
--------------------------------------------------------------------------------
[179]26
--------------------------------------------------------------------------------
[180]
--------------------------------------------------------------------------------
[181]
--------------------------------------------------------------------------------
[182]14
--------------------------------------------------------------------------------
[183]
--------------------------------------------------------------------------------
[184]
--------------------------------------------------------------------------------
[185]Sleepless In A Hotel Room | Luke Combs
--------------------------------------------------------------------------------
[186]
--------------------------------------------------------------------------------
[187]11
--------------------------------------------------------------------------------
[188]11
--------------------------------------------------------------------------------
[189]12
--------------------------------------------------------------------------------
[190]
--------------------------------------------------------------------------------
[191]11
--------------------------------------------------------------------------------
[192]11
--------------------------------------------------------------------------------
[193]12
--------------------------------------------------------------------------------
[194]
--------------------------------------------------------------------------------
[195]
--------------------------------------------------------------------------------
[196]15
--------------------------------------------------------------------------------
[197]
--------------------------------------------------------------------------------
[198]
--------------------------------------------------------------------------------
[199]Risk It All | Bruno Mars
--------------------------------------------------------------------------------
[200]
--------------------------------------------------------------------------------
[201]15
--------------------------------------------------------------------------------
[202]4
--------------------------------------------------------------------------------
[203]5
--------------------------------------------------------------------------------
[204]
--------------------------------------------------------------------------------
[205]15
--------------------------------------------------------------------------------
[206]4
--------------------------------------------------------------------------------
[207]5
--------------------------------------------------------------------------------
[208]
--------------------------------------------------------------------------------
[209]
--------------------------------------------------------------------------------
[210]16
--------------------------------------------------------------------------------
[211]
--------------------------------------------------------------------------------
[212]
--------------------------------------------------------------------------------
[213]Babydoll | Dominic Fike
--------------------------------------------------------------------------------
[214]
--------------------------------------------------------------------------------
[215]16
--------------------------------------------------------------------------------
[216]16
--------------------------------------------------------------------------------
[217]8
--------------------------------------------------------------------------------
[218]
--------------------------------------------------------------------------------
[219]16
--------------------------------------------------------------------------------
[220]16
--------------------------------------------------------------------------------
[221]8
--------------------------------------------------------------------------------
[222]
--------------------------------------------------------------------------------
[223]
--------------------------------------------------------------------------------
[224]17

In [10]:
### for thru span class
billboard = [x.get_text(strip=True) for x in soup.select("li.o-chart-results-list__item")]
billboard = [x for x in billboard if x]
billboard

['1',
 "Choosin' TexasElla Langley",
 '2',
 '1',
 '24',
 '2',
 '1',
 '24',
 '2',
 'SwimBTS',
 '1',
 '1',
 '2',
 '1',
 '1',
 '2',
 '3',
 'Man I NeedOlivia Dean',
 '3',
 '2',
 '32',
 '3',
 '2',
 '32',
 '4',
 'I Just MightBruno Mars',
 '4',
 '1',
 '12',
 '4',
 '1',
 '12',
 '5',
 'OrdinaryAlex Warren',
 '5',
 '1',
 '59',
 '5',
 '1',
 '59',
 '6',
 'So Easy (To Fall In Love)Olivia Dean',
 '7',
 '6',
 '27',
 '7',
 '6',
 '27',
 '7',
 'GoldenHUNTR/X: EJAE, Audrey Nuna & REI AMI',
 '6',
 '1',
 '41',
 '6',
 '1',
 '41',
 '8',
 'StatesidePinkPantheressWithZara Larsson',
 '8',
 '6',
 '13',
 '8',
 '6',
 '13',
 '9',
 'The Fate Of OpheliaTaylor Swift',
 '9',
 '1',
 '26',
 '9',
 '1',
 '26',
 '10',
 'FoldedKehlani',
 '10',
 '6',
 '42',
 '10',
 '6',
 '42',
 '11',
 'Where Is My Husband!RAYE',
 '17',
 '11',
 '27',
 '17',
 '11',
 '27',
 '12',
 'Be HerElla Langley',
 '13',
 '12',
 '7',
 '13',
 '12',
 '7',
 '13',
 'OpaliteTaylor Swift',
 '12',
 '1',
 '26',
 '12',
 '1',
 '26',
 '14',
 'Sleepless In A Hotel RoomLuke Combs',
 '11',
 '11',
 '12',
 '11',
 '11',
 '12',
 '15',
 'Risk It AllBruno Mars',
 '15',
 '4',
 '5',
 '15',
 '4',
 '5',
 '16',
 'BabydollDominic Fike',
 '16',
 '16',
 '8',
 '16',
 '16',
 '8',
 '17',
 'IloveitiloveitiloveitBella Kay',
 '20',
 '17',
 '7',
 '20',
 '17',
 '7',
 '18',
 'DraculaTame Impala&JENNIE',
 '24',
 '18',
 '27',
 '24',
 '18',
 '27',
 '19',
 'E85Don Toliver',
 '21',
 '15',
 '9',
 '21',
 '15',
 '9',
 '20',
 'YukonJustin Bieber',
 '23',
 '17',
 '38',
 '23',
 '17',
 '38',
 '21NEW',
 'NEW',
 'FatherYe &Travis Scott',
 '-',
 '21',
 '1',
 '-',
 '21',
 '1',
 '22',
 'Be By YouLuke Combs',
 '18',
 '12',
 '7',
 '18',
 '12',
 '7',
 '23',
 'American GirlsHarry Styles',
 '19',
 '4',
 '4',
 '19',
 '4',
 '4',
 '24',
 'DTMFBad Bunny',
 '22',
 '1',
 '29',
 '22',
 '1',
 '29',
 '25',
 'Homewreckersombr',
 '26',
 '24',
 '8',
 '26',
 '24',
 '8',
 '26',
 'BodyDon Toliver',
 '27',
 '14',
 '9',
 '27',
 '14',
 '9',
 '27NEW',
 'NEW',
 'All The LoveYe &Andre Troutman',
 '-',
 '27',
 '1',
 '-',
 '27',
 '1',
 '28',
 'The FallCody Johnson',
 '30',
 '28',
 '27',
 '30',
 '28',
 '27',
 '29',
 'Die On This HillSienna Spiro',
 '29',
 '19',
 '15',
 '29',
 '19',
 '15',
 '30',
 'Change My MindRiley Green',
 '38',
 '30',
 '9',
 '38',
 '30',
 '9',
 '31',
 'Pop Dat ThangDaBaby',
 '45',
 '31',
 '9',
 '45',
 '31',
 '9',
 '32',
 'White KeysDominic Fike',
 '32',
 '32',
 '6',
 '32',
 '32',
 '6',
 '33',
 'Fever DreamAlex Warren',
 '33',
 '21',
 '5',
 '33',
 '21',
 '5',
 '34',
 "Let 'Em KnowT.I.",
 '40',
 '34',
 '10',
 '40',
 '34',
 '10',
 '35',
 'Elizabeth TaylorTaylor Swift',
 '65',
 '3',
 '22',
 '65',
 '3',
 '22',
 '36',
 'Lush LifeZara Larsson',
 '44',
 '36',
 '16',
 '44',
 '36',
 '16',
 '37',
 'What You SayingLil Uzi Vert',
 '34',
 '12',
 '14',
 '34',
 '12',
 '14',
 '38',
 'The Great DivideNoah Kahan',
 '37',
 '6',
 '9',
 '37',
 '6',
 '9',
 '39',
 'Days Like TheseLuke Combs',
 '31',
 '31',
 '23',
 '31',
 '31',
 '23',
 '40NEW',
 'NEW',
 'KingYe',
 '-',
 '40',
 '1',
 '-',
 '40',
 '1',
 '41',
 'Motion PartyBossMan Dlow',
 '48',
 '41',
 '3',
 '48',
 '41',
 '3',
 '42',
 'Body To BodyBTS',
 '25',
 '25',
 '2',
 '25',
 '25',
 '2',
 '43',
 'Midnight SunZara Larsson',
 '49',
 '39',
 '11',
 '49',
 '39',
 '11',
 '44NEW',
 'NEW',
 'Punch DrunkYe',
 '-',
 '44',
 '1',
 '-',
 '44',
 '1',
 '45',
 'BrunetteTucker Wetmore',
 '51',
 '44',
 '14',
 '51',
 '44',
 '14',
 '46',
 'Loving Life AgainElla Langley',
 '55',
 '46',
 '2',
 '55',
 '46',
 '2',
 '47',
 'McArthurHARDY,Eric Church,Morgan Wallen&Tim McGraw',
 '54',
 '31',
 '9',
 '54',
 '31',
 '9',
 '48',
 'Porch LightNoah Kahan',
 '42',
 '20',
 '3',
 '42',
 '20',
 '3',
 '49NEW',
 'NEW',
 'Whatever WorksYe',
 '-',
 '49',
 '1',
 '-',
 '49',
 '1',
 '50',
 'When Did You Get Hot?Sabrina Carpenter',
 '58',
 '17',
 '29',
 '58',
 '17',
 '29',
 '51NEW',
 'NEW',
 'This A MustYe',
 '-',
 '51',
 '1',
 '-',
 '51',
 '1',
 '52',
 'RaindanceDave&Tems',
 '57',
 '52',
 '9',
 '57',
 '52',
 '9',
 '53',
 'ChanelTyla',
 '59',
 '43',
 '16',
 '59',
 '43',
 '16',
 '54',
 'DandelionElla Langley',
 '60',
 '37',
 '9',
 '60',
 '37',
 '9',
 '55',
 'Rethink Some ThingsLuke Combs',
 '46',
 '46',
 '2',
 '46',
 '46',
 '2',
 '56',
 "I Ain't Coming BackMorgan WallenFeaturingPost Malone",
 '66',
 '8',
 '42',
 '66',
 '8',
 '42',
 '57NEW',
 'NEW',
 'Preacher ManYe',
 '-',
 '57',
 '1',
 '-',
 '57',
 '1',
 '58',
 'ApertureHarry Styles',
 '39',
 '1',
 '10',
 '39',
 '1',
 '10',
 '59NEW',
 'NEW',
 "Mama's FavoriteYe",
 '-',
 '59',
 '1',
 '-',
 '59',
 '1',
 '60',
 'In My RoomJulia Wolf',
 '67',
 '60',
 '4',
 '67',
 '60',
 '4',
 '61NEW',
 'NEW',
 'BullyYe & CeeLo Green',
 '-',
 '61',
 '1',
 '-',
 '61',
 '1',
 '62NEW',
 'NEW',
 'Highs And LowsYe',
 '-',
 '62',
 '1',
 '-',
 '62',
 '1',
 '63',
 "Time's TickingJustin Moore",
 '75',
 '63',
 '7',
 '75',
 '63',
 '7',
 '64',
 'HooliganBTS',
 '35',
 '35',
 '2',
 '35',
 '35',
 '2',
 '65',
 'EarringsMalcolm Todd',
 '85',
 '65',
 '5',
 '85',
 '65',
 '5',
 '66',
 "What He'll Never HaveDylan Scott",
 '74',
 '66',
 '5',
 '74',
 '66',
 '5',
 '67NEW',
 'NEW',
 'Sisters And BrothersYe',
 '-',
 '67',
 '1',
 '-',
 '67',
 '1',
 '68',
 "Ain't A Bad LifeThomas RhettFeaturingJordan Davis",
 '71',
 '65',
 '9',
 '71',
 '65',
 '9',
 '69NEW',
 'NEW',
 'Younger You (From The "Hannah Montana 20th Anniversary Special")Miley Cyrus',
 '-',
 '69',
 '1',
 '-',
 '69',
 '1',
 '70',
 'Turn This Truck AroundJordan Davis',
 '73',
 '69',
 '5',
 '73',
 '69',
 '5',
 '71',
 'Beautiful ThingsMegan Moroney',
 '72',
 '32',
 '18',
 '72',
 '32',
 '18',
 '72NEW',
 'NEW',
 "I Can't WaitYe",
 '-',
 '72',
 '1',
 '-',
 '72',
 '1',
 '73',
 'NormalBTS',
 '41',
 '41',
 '2',
 '41',
 '41',
 '2',
 '74',
 'FYABTS',
 '36',
 '36',
 '2',
 '36',
 '36',
 '2',
 '75',
 '2.0BTS',
 '50',
 '50',
 '2',
 '50',
 '50',
 '2',
 '76',
 'Ends Of The EarthTy Myers',
 '76',
 '72',
 '11',
 '76',
 '72',
 '11',
 '77',
 "Freakin' OutDexter And The Moonrocks",
 '91',
 '77',
 '2',
 '91',
 '77',
 '2',
 '78',
 'Rein Me InSam Fender& Olivia Dean',
 '78',
 '77',
 '3',
 '78',
 '77',
 '3',
 '79',
 'Coming Up RosesHarry Styles',
 '64',
 '18',
 '4',
 '64',
 '18',
 '4',
 '80',
 'The VisitorSienna Spiro',
 '62',
 '43',
 '3',
 '62',
 '43',
 '3',
 '81NEW',
 'NEW',
 'Last BreathYe &Peso Pluma',
 '-',
 '81',
 '1',
 '-',
 '81',
 '1',
 '82NEW',
 'NEW',
 'White LinesYe &Andre Troutman',
 '-',
 '82',
 '1',
 '-',
 '82',
 '1',
 '83',
 'Go AwayWeezer',
 '90',
 '83',
 '2',
 '90',
 '83',
 '2',
 '84',
 'AliensBTS',
 '47',
 '47',
 '2',
 '47',
 '47',
 '2',
 '85NEW',
 'NEW',
 'Beauty And The BeastYe',
 '-',
 '85',
 '1',
 '-',
 '85',
 '1',
 '86',
 "Don't WeMorgan Wallen",
 '88',
 '48',
 '8',
 '88',
 '48',
 '8',
 '87NEW',
 'NEW',
 'CirclesYe',
 '-',
 '87',
 '1',
 '-',
 '87',
 '1',
 '88',
 'Dry SpellKacey Musgraves',
 '80',
 '55',
 '3',
 '80',
 '55',
 '3',
 '89',
 'What You NeedTems',
 '98',
 '89',
 '3',
 '98',
 '89',
 '3',
 '90',
 'Like AnimalsBTS',
 '53',
 '53',
 '2',
 '53',
 '53',
 '2',
 '91',
 'ZooShakira',
 '81',
 '73',
 '8',
 '81',
 '73',
 '8',
 '92',
 'DanoPeso Pluma& Tito Double P',
 '87',
 '75',
 '6',
 '87',
 '75',
 '6',
 '93',
 'Who KnowsDaniel Caesar',
 '83',
 '52',
 '13',
 '83',
 '52',
 '13',
 '94',
 "They Don't Know 'bout UsBTS",
 '56',
 '56',
 '2',
 '56',
 '56',
 '2',
 '95',
 'Mrs. TrendsetterLil Baby',
 '84',
 '64',
 '7',
 '84',
 '64',
 '7',
 '96',
 'Merry Go RoundBTS',
 '52',
 '52',
 '2',
 '52',
 '52',
 '2',
 '97NEW',
 'NEW',
 'GriddleYeat &Don Toliver',
 '-',
 '97',
 '1',
 '-',
 '97',
 '1',
 '98NEW',
 'NEW',
 'Silent TreatmentFreya Skye',
 '-',
 '98',
 '1',
 '-',
 '98',
 '1',
 '99',
 'Taste BackHarry Styles',
 '69',
 '17',
 '4',
 '69',
 '17',
 '4',
 '100',
 'Plastic CigaretteZach Bryan',
 '89',
 '13',
 '11',
 '89',
 '13',
 '11']

In [11]:
### this is when i learned i needed to go a diff route
### when there's a new song on the list. they mess with the indexes

rank = billboard[0::8]
# title_artist = billboard[3::14]
# lw = billboard[5::14]
# peak = billboard[6::14]
# weeks = billboard[7::14]

billboard_df = pd.DataFrame({
    "Rank": rank
    # "Title/Artist": title_artist,
    # "LW": lw,
    # "Peak": peak,
    # "Weeks": weeks
})

billboard_df.head(54)

     Rank
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9
9      10
10     11
11     12
12     13
13     14
14     15
15     16
16     17
17     18
18     19
19     20
20  21NEW
21      1
22      7
23      4
24     29
25      8
26      9
27     27
28     28
29     19
30     30
31     31
32     32
33     21
34     34
35      3
36     36
37     12
38      6
39     31
40      -
41     48
42     25
43     49
44      1
45     14
46      2
47      9
48      3
49     49
50     17
51      -
52     57
53     59